sudo: required

language: java

jdk: openjdk11

git:
  depth: 9999999

services:
  - docker

before_script:
  - bash ./.travis/install-postgres-11.sh

script:
  - ./mvnw clean package

deploy:
  skip_cleanup: true
  provider: script
  script:
    echo "$DOCKER_PASS" | docker login docker.pkg.github.com -u "$DOCKER_USER" --password-stdin;
    docker build -t docker.pkg.github.com/svindicium/cms/cms:stable .;
    docker push docker.pkg.github.com/svindicium/cms/cms:stable;
  on:
    all_branches: true

cache:
  directories:
    - '$HOME/.m2/repository'
