sudo: required

language: java

jdk: openjdk11

git:
  depth: 9999999

env:
  global:
    - secure: "Q+EHuVnHz3qXCRGETbDF+T6XHjpQPrcjS8tlQPik1TFaqzUgF9b+6vu69XEvDdAWVriVpQVKoM+FOyOD017JQpkDyUeEbxdatuKT9QCjXBWd0w3oBCMCpxJ+VqLxWQl7nbCMXO0GraEtPbIjSYE8IVekcfTu5uJ2WAqa1nO7Uyl3orsAjoRA8fDSqLz+woLO5lid352oorkszjPOD4MGnKpxmY6gAHGsI1EPq4U2aVaNhhmEkKxXSJhP9faWLd44gIM0VWzVZwFiqTCYnqvCT4HXWvOkNiRtGIN+MfNLb6HKr0BTFoDHn8WurbwKqCDJDB1TR0dYt0IYASPkxky0Op9XiQH3VJ00/GxgT6IiDixO5g/RqgQdyj2FatumuNRpxNb9iCnQBjZOuxgNmwAIYF41IwOd6MA8xJQr9o1tSp+gSGZaP18E974r5ktQVfTxnTu9NgQei+cmUo9kDtFvSa/cANBUwdQoT1f5dOraSuvJFtTL0vBmSggCGRYrk966H5Wd0w6zVFaf9RkhtYYovJvjHlHF2pixmbwneDSSRsMsHJZ6DONgryKO6TPPpL4gRLHHgpsrVf8NytSQa/v+rOJpxl5jNq8BHceuTo4SwaHWEXB5iD8boMk0Mt86RC+WfLy4Rt5Jz4D/SSFW0dDyRIDgEbDc3TmgoLDq9Cvq3CY="
    - secure: "RlBfjdYgjH6nTbH1/ZnwYR8MtnAPVLA682xDRYypoNNC9Ow9DP7mFLh5zt7aAnJNy/64GZqviUwsFayEfGleYk9sY4CWAc8wsXOvxMvnMTWlXLv1pifJIExREWECKVhLcMEgQ8kEnQSigSDo1FwVM2dhZzRAXGxc6DwbXyzF4trMM1uvACwyJReji590rLE03K+NuhF5FrY8SQJBrV/ICHTM3LFJPjexFN+J0Lpj412TfKhhWh4RLOy4cVlg3uzyRk12ErPgH1m1jBjHNvugHkouZLUDBkJsD+ccRpRWDmUJ3jycQoWKHMi/UCBX/bUk1rnGgn2aGQKdqJTfday3HOENmvdqOOn3vNQlMzuwMwnZSnj5T6YDPizUOA8lAJPxgQ2T4e1JZ0NWHYKvZL9pS+DIIvkAm8hyII2IzOnzJ12W5jtleq5wnqVfVcImu0Qh4lIHReHiAAwWFaWMo8BhuVQjkHvn21EP02YwLrlFF3fhtEfWEEnL5LmmjR29cfimM//Gg75h73oxA+UTQKa6wA8pFFs4VTNVEv+OAQqeRtD3MWWyrZylJqVhF2ewSGzoVsL+kDnEbu6iMC4SIq0Cv4noRsi8muaYFQqqkmxFugsGGSbhqJ97p+2E6OukzilHYI3HkGev75oxcvIVQDYR/6c804XHlSfeBeoNmzFIQCs="

services:
  - docker

before_script:
  - bash ./.travis/install-postgres-11.sh

script:
  - ./mvnw clean package
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "stable"; elif [ "$TRAVIS_BRANCH" == "dev" ]; then echo "latest"; else echo $TRAVIS_BRANCH | tr "/" -; fi`

deploy:
  skip_cleanup: true
  provider: script
  script:
    echo "$DOCKER_PASS" | docker login docker.pkg.github.com -u "$DOCKER_USER" --password-stdin;
    docker build -t docker.pkg.github.com/svindicium/cms/cms:$TAG .;
    docker push docker.pkg.github.com/svindicium/cms/cms:$TAG;
  on:
    all_branches: true

cache:
  directories:
    - '$HOME/.m2/repository'
