sudo: required

language: java

jdk: openjdk11

git:
  depth: 9999999

env:
  global:
    - secure: "UuldWkFzBkk5yI0Ss9Ppp4lUUgKd3u40+YBp12W0/w2MryaBHjUauRXGb52xc6krsRa2sLWgqmCsC/lauxAK5ylLr6EeEeYVCE+SrcUrP2p3ZboXT4dzW93S7Luv/Ti2/vNXJ9LmF3BHDLOj1spXav7WyV0m5m4XWt/OwkoFGyJvQUQFRLtA/UIwNF56DELfjBMhPeNKDLAp6PrqpvMYRvTqjti3h0nZIwxXz4OqmXjiOuMKsWKlBqzs6Yxx6jAK3KKCbgtTZE3A4ggIajwhESVPjLBtccLp1YIYIEQyOsH6+J0TQxrYLg2/zypJPQzTCtKIhS37iJVf8GDdGklj9nKuMrCAGwN+Wd2J4YsFbo6qPiuUocQ9RGjsiOglgI/FPeEqTtYVgbqfFu0FY66lUA2+veMOm+VP3PxjBU1e2zFocDlFywQLTSSRp7Z1tkC32dZBpBxHpDXvJFUKTWicAx441oUsb1uYIGhenCv+ibJunrZ/FYZSHigUpxsQBeF4z9+VisxnyZeroOnCBeWzw7RdcDiseoMF7tF+mnyJVDkifnYwdt+sccUjW2XIjbu+oNgZc5/k/DNLmHM6hmYzQDRxrYNJ9At9LASY0ABikIbg6eOK1swokpOs1B+1vAvGPa2b4VyJai8QbiKTbelm/vcT0ZuI6lc3hwWntJNIdE4="
    - secure: "WNfnHurwSRe+RdxtrHxrtvEpUTArxRARKW4aza+ftOwcEtPBW7CtMJqaPZIB+yXH9pOTE8hz+7EFTbCIVc0ZSCdBDwyW1rsyZbT7CU26Wfmi96N391BSKX14jXlSiMtjMgQh3zTl2k7jWYOkgM4N0ft5Z/aKGJMPXx/4J8dxP8/N04IZ56XB+wczcYdOXbiUDIFRmCk7cxLnIUYK2mN9/FkThC02ZIf8JrLGQ6GCMPgru6up/p/0JugWnOneDa3WlMNrNI3IX71HAw6YYijLZ6a4wEPUfDLsty1VfDrQtaDmFQkYTYbZOeqyKWMfF235BEsRxYCuQv/AZqYFX31yENR4bvynffL75hTcUpCuMva/xpKe7P8tuLguver+MnSCsX9a30eQlhSdKEYZLFqtpCjOlojeWWlciFFOfdmdmYuFiDOFYpik/DE8bvvOYcuJNQ+DObNYXyCVp6Yo9L5ynwpRBIHlr2HwnqQa85lG+6Ol3WCxOJ73CIkj0cVUYDnT9XS36Je4YIEcJOPY/09pzqhuNDIqEICq8i1VU158eJrfY5iArjDsBcXXTB04+wLMGEtsKQ6ztr7FIa53iuukXr/kNJSEzGabaSMEANH2VyuQ44w+HlL80/LDU3yQ5emFL5cLeDoxhHPGStoh670CreiZgNX/LGdJoFRBdrPT4Rk="

services:
  - docker

before_script:
  - bash ./.travis/install-postgres-11.sh

script:
  - ./mvnw clean package
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "stable"; elif [ "$TRAVIS_BRANCH" == "dev" ]; then echo "latest"; else echo $TRAVIS_BRANCH | tr "/" -; fi`

deploy:
  skip_cleanup: true
  provider: script
  script:
    echo "$DOCKER_PASS" | docker login docker.pkg.github.com -u "$DOCKER_USER" --password-stdin;
    docker build -t docker.pkg.github.com/svindicium/cms/cms:$TAG .;
    docker push docker.pkg.github.com/svindicium/cms/cms:$TAG;
  on:
    all_branches: true

cache:
  directories:
    - '$HOME/.m2/repository'
